version: "3"
services:
  nginx:
    container_name: discount_api_nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports: 
      - "8080:80"
    networks:
      - internal
    volumes:
      - .:/var/www/html
      - ./logs/nginx:/var/log/nginx/
    depends_on:
      - php
  php:
    container_name: discount_api_php
    build:
      context: .
      dockerfile: php/Dockerfile
    networks:
      - internal
    volumes:
      - .:/var/www/html
      - ./logs/php.log:/var/log/fpm-php.www.log
  mysql:
    container_name: discount_api_mysql
    image: mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
        MYSQL_DATABASE: discount_api
        MYSQL_USER: MYSQL_USER
        MYSQL_PASSWORD: MYSQL_PASSWORD
    ports:
        - "3306:3306"

networks:
  internal:
    driver: bridge